
services:
  mosquitto:
    image: dhi.io/eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - vineyard-network

  ingestor:
    build: 
      context: .
      dockerfile: ./ingestor/Dockerfile
    container_name: data_ingestor
    depends_on:
      - mosquitto
      - kafka
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=uva/mesa/vitoria/leitura
      - KAFKA_BOOTSRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=uva_mesa_vitoria
    restart: always
    volumes:
      - .:/usr/src/app/
      - ./ingestor/log/log.log:/usr/src/app/log/log.log
    networks:
      - vineyard-network

  preprocessor:
    build: 
      context: .
      dockerfile: ./pre_processor/Dockerfile
    container_name: pre_processor
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=uva_mesa_vitoria
      - KAFKA_GROUP_ID=data-processing-group
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=token
      - INFLUXDB_ORG=vinhedo
      - INFLUXDB_BUCKET=sensor_data
      - POSTGRES_HOST=postgres 
      - POSTGRES_DB=leituras_vinhedo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - AGREGAR_MINUTOS=15
    depends_on:
      - kafka
      - flink-jobmanager
      - influxdb
      - postgres
    volumes:
      - .:/usr/src/app/
      - ./pre_processor/log/log.log:/usr/src/app/log/log.log
    networks:
      - vineyard-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vineyard-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - vineyard-network

  flink-jobmanager:
    image: flink:2.2.0-scala_2.12-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - vineyard-network

  flink-taskmanager:
    image: flink:2.2.0-scala_2.12-java11
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on:
      - flink-jobmanager
    networks:
      - vineyard-network

  influxdb:
    image: influxdb:3-core
    ports:
      - "8086:8086"
    command: >
      --node-id-from-env INFLUXDB_ID
      --log-filter info
    environment:
      - INFLUXDB_ID=vinhedo
      - INFLUXDB_INIT_MODE= setup
      - INFLUXDB_INIT_USERNAME=admin
      - INFLUXDB_INIT_PASSWORD=admin
      - INFLUXDB3_ENTERPRISE_LICENSE_EMAIL=youremail@youremail
      - INFLUXDB_INIT_ORG=vinhedo
      - INFLUXDB_INIT_BUCKET=sensor_data
      - INFLUXDB_INIT_ADMIN_TOKEN=token
    volumes:
      - influxdb-data:/var/lib/influxdb3
    networks:
      - vineyard-network

  postgres:
    image: postgres:18.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=leituras_vinhedo
    networks:
      - vineyard-network
    volumes:
      - postgres-data:/var/lib/postgresql
      - .postgres/init-scripts:/docker-entrypoint-initdb.d:ro


  grafana:
    image: grafana/grafana:12.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/grafana_storage:/var/lib/grafana
    depends_on:
      - influxdb
      - postgres
    networks:
      - vineyard-network

networks:
  vineyard-network:
    driver: bridge

volumes:
  influxdb-data:
  postgres-data:
