
services:
  mosquitto:
    image: dhi.io/eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/data:/mosquitto/data/
      - ./mosquitto/log:/mosquitto/log/
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-p", "1883", "-t", "healthcheck", "-m", "ok"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - vineyard-network

  ingestor:
    build: ingestor
    container_name: data_ingestor
    depends_on:
      mosquitto:
        condition: service_healthy
        restart: true
      kafka-init:
        condition: service_completed_successfully
        restart: true
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=uva/mesa/vitoria/leitura
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=uva_mesa_vitoria
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - ./models:/usr/src/app/models
      - ./ingestor/log/log.log:/usr/src/app/log/log.log
    networks:
      - vineyard-network

  preprocessor:
    build: pre_processor
    container_name: pre_processor
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=uva_mesa_vitoria
      - KAFKA_GROUP_ID=data-processing-group
      - INFLUXDB_URL=http://influxdb:8181
      - INFLUXDB_DB=vinhedo
      - INFLUXDB_BUCKET=sensor_data
      - INFLUXDB_HOST=influxdb
      - POSTGRES_HOST=postgres 
      - POSTGRES_DB=leituras_vinhedo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      flink-jobmanager:
        condition: service_healthy
        restart: true
      influxdb:
        condition: service_healthy
        restart: true
      kafka-init:
        condition: service_completed_successfully
        restart: true
    volumes:
      - ./models:/usr/src/app/models
      - ./pre_processor/log/log.log:/usr/src/app/log/log.log
    networks:
      - vineyard-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - vineyard-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "uva_mesa_vitoria:1:1"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vineyard-network

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    command: sh -c "sleep 15 && kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic uva_mesa_vitoria --partitions 1 --replication-factor 1"
    init: true
    networks:
      - vineyard-network

  flink-jobmanager: 
    build: ./flink
    ports:
      - "8081:8081"
    command: 
      - jobmanager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://flink-jobmanager:8081/overview"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - vineyard-network

  flink-taskmanager:
    build: ./flink
    command: 
      - taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2
    depends_on:
      - flink-jobmanager
    networks:
      - vineyard-network

  influxdb:
    image: influxdb:3-core
    ports:
      - "8181:8181"
    environment:
      - INFLUXDB_NODE_ID=node0;
      - INFLUXDB_ORG=vinhedo
      - INFLUXDB_BUCKET=sensor_data
    command: 
      - influxdb3
      - serve
      - --node-id=INFLUXDB_NODE_ID
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://influxdb:8181/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./influxdb-data:/var/lib/influxdb3
    networks:
      - vineyard-network

  postgres:
    image: postgres:18.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=leituras_vinhedo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d leituras_vinhedo"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - vineyard-network
    volumes:
      - postgres-data:/var/lib/postgresql
      - .postgres/init-scripts:/docker-entrypoint-initdb.d:ro


  grafana:
    image: grafana/grafana:12.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/grafana_storage:/var/lib/grafana
    depends_on:
      - influxdb
      - postgres
    networks:   
      - vineyard-network

networks:
  vineyard-network:
    driver: bridge

volumes:
  influxdb-data:
  postgres-data:
